stream_over_http_enabled: true
server:
  http_listen_port: 3200
  log_level: ${GRAFANA_TEMPO_LOG_LEVEL}
query_frontend:
  search:
    duration_slo: 5s
    throughput_bytes_slo: 1.073741824e+09
    metadata_slo:
      duration_slo: 5s
      throughput_bytes_slo: 1.073741824e+09
  trace_by_id:
    duration_slo: 5s
distributor:
  receivers:
    otlp:
      protocols:
        grpc:
          endpoint: "${GRAFANA_TEMPO_HOST}:4317"
ingester:
  max_block_duration: 5m
compactor:
  compaction:
    block_retention: 1h
metrics_generator:
  registry:
    external_labels:
      source: tempo
      cluster: docker-compose
  storage:
    path: /var/tempo/generator/wal
    remote_write:
      - url: http://${PROMETHEUS_HOST}:9090/api/v1/write
        send_exemplars: true
  traces_storage:
    path: /var/tempo/generator/traces
storage:
  trace:
    backend: local
    wal:
      path: /var/tempo/wal
    local:
      path: /var/tempo/blocks
overrides:
  defaults:
    metrics_generator:
      processors: [service-graphs, span-metrics, local-blocks]
      generate_native_histograms: both
