services:
  database:
    image: mysql:8.1
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_USER: "${MYSQL_USERNAME:-root}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_PASSWORD:-root}"
      MYSQL_DATABASE: "${MYSQL_DATABASE:-widget}"
    healthcheck:
      test: "mysqladmin ping --host 127.0.0.1 --user $$MYSQL_ROOT_USER -p$$MYSQL_ROOT_PASSWORD"
      interval: 10s
      timeout: 20s
      retries: 10
  openobserve:
    image: public.ecr.aws/zinclabs/openobserve:latest
    container_name: "${OPENOBSERVE_CONTAINER_NAME:-openobserve}"
    ports:
      - "${OPENOBSERVE_PORT:-5080}:5080"
    environment:
      ZO_ROOT_USER_EMAIL: "${OPENOBSERVE_USERNAME:-root@example.com}"
      ZO_ROOT_USER_PASSWORD: "${OPENOBSERVE_PASSWORD:-Complexpass#123}"
  opentelemetry-collector:
    image: otel/opentelemetry-collector:0.88.0
    ports:
      - "${OPENTELEMETRY_COLLECTOR_GRPC_PORT:-5317}:4317"
    volumes:
      - ./config/opentelemetry-collector/config.yaml:/etc/config.yaml
    environment:
      OPENOBSERVE_HOST: "${OPENOBSERVE_CONTAINER_NAME:-openobserve}"
      OPENOBSERVE_PORT: "5081"
      OPENOBSERVE_AUTH: "cm9vdEBleGFtcGxlLmNvbTpDb21wbGV4cGFzcyMxMjM=" # `echo -n 'root@example.com:Complexpass#123' | base64`
    command: ["--config=/etc/config.yaml"]
