[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
lib = { version = "0.1.0", path = "../lib" }
mockall = { version = "0.12.1", optional = true }
thiserror = "1.0.56"
ulid = "1.1.2"

[features]
test = []
mockall = ["dep:mockall"]
