[package]
name = "driver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
app = { version = "0.1.0", path = "../app" }
axum = "0.7.4"
lib = { version = "0.1.0", path = "../lib" }
serde_json = "1.0.113"
tokio = { version = "1.36.0", default-features = false, features = ["signal"] }
