apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    orgId: 1
    url: http://${PROMETHEUS_HOST}:9090
    basicAuth: false
    isDefault: false
    version: 1
    editable: false
    jsonData:
      httpMethod: GET
  - name: Tempo
    type: tempo
    access: proxy
    orgId: 1
    url: http://${GRAFANA_TEMPO_HOST}:3200
    basicAuth: false
    isDefault: true
    version: 1
    editable: false
    apiVersion: 1
    uid: tempo
    jsonData:
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: "-15m"
        spanEndTimeShift: "15m"
        filterByTraceID: false
        filterBySpanID: false
        customQuery: true
        query: '{ service_name != "" } | trace_id = "$${__trace.traceId}"'
      httpMethod: GET
      serviceMap:
        datasourceUid: prometheus
      streamingEnabled:
        search: true
  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://${GRAFANA_LOKI_HOST}:3100
    editable: true
