[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
mockall = { version = "0.12.1", optional = true }
thiserror.workspace = true
uuid = { version = "1.10.0", features = ["v7"] }

[features]
command = []
mockall = ["dep:mockall"]

[lints]
workspace = true
