receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ${env:OPENTELEMETRY_COLLECTOR_HOST}:4317
processors:
  batch:
exporters:
  otlp/gateway:
    endpoint: ${env:OPENTELEMETRY_COLLECTOR_GATEWAY_HOST}:4317
    tls:
      insecure: true
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/gateway]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/gateway]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/gateway]
  telemetry:
    metrics:
      level: detailed
      readers:
        - periodic:
            interval: 5000
            exporter:
              otlp:
                protocol: http/protobuf
                endpoint: http://${env:PROMETHEUS_HOST}:9090/api/v1/otlp/v1/metrics
