receivers:
  otlp:
    protocols:
      grpc:
  prometheus/otel-collector:
    config:
      scrape_configs:
        - job_name: "opentelemetry-collector"
          scrape_interval: 10s
          static_configs:
            - targets: ["0.0.0.0:8888"]
processors:
  batch:
exporters:
  logging:
    loglevel: debug
  otlp/openobserve:
    endpoint: "${env:OPENOBSERVE_HOST}:${env:OPENOBSERVE_PORT}"
    headers:
      Authorization: "Basic ${env:OPENOBSERVE_AUTH}"
      organization: default
      stream-name: default
    tls:
      insecure: true
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp/openobserve]
    metrics:
      receivers: [otlp, prometheus/otel-collector]
      processors: [batch]
      exporters: [logging, otlp/openobserve]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [logging, otlp/openobserve]
