receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ${env:OPENTELEMETRY_COLLECTOR_HOST}:4317
processors:
  batch:
exporters:
  otlp/traces:
    endpoint: ${env:GRAFANA_TEMPO_HOST}:4317
    tls:
      insecure: true
  otlphttp/metrics:
    metrics_endpoint: http://${env:PROMETHEUS_HOST}:9090/api/v1/otlp/v1/metrics
    tls:
      insecure: true
  otlphttp/logs:
    endpoint: http://${env:GRAFANA_LOKI_HOST}:3100/otlp
    tls:
      insecure: true
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/traces]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/metrics]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/logs]
