[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.95", default-features = false }
thiserror = "1.0.65"
tracing = "0.1.41"
uuid = { version = "1.13.2", features = ["v4"] }

[dev-dependencies]
pretty_assertions = "1.4.1"

[lints]
workspace = true
