[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.95", default-features = false }
thiserror = "1.0.65"
uuid = { version = "1.13.2", features = ["v4"] }

[lints]
workspace = true
